version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=staging
    environment:
      - NODE_ENV=staging
    volumes:
      - ./storage/staging:/usr/src/app/storage
      - ./logs/staging:/usr/src/app/logs
    command: ["npm", "run", "start:staging"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M

  neo4j:
    environment:
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_pagecache_size=512M
    volumes:
      - neo4j-staging-data:/data
      - neo4j-staging-logs:/logs
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

  prometheus:
    volumes:
      - ./monitoring/prometheus/staging:/etc/prometheus
      - prometheus-staging-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M

  grafana:
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_DISABLE_LOGIN_FORM=false
    volumes:
      - grafana-staging-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards/staging:/var/lib/grafana/dashboards
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M

  # Additional service for load testing
  k6:
    image: grafana/k6:latest
    volumes:
      - ./tests/load:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    depends_on:
      - influxdb
    profiles:
      - testing

  # InfluxDB for storing load test results
  influxdb:
    image: influxdb:1.8
    environment:
      - INFLUXDB_DB=k6
    volumes:
      - influxdb-staging-data:/var/lib/influxdb
    profiles:
      - testing
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M

volumes:
  neo4j-staging-data:
  neo4j-staging-logs:
  prometheus-staging-data:
  grafana-staging-data:
  influxdb-staging-data:

networks:
  default:
    name: evidenceai-staging
